{
 "title": "Minecraft Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cpu" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "total_memory - free_memory", "legendFormat": "Memory Used" },
    { "expr": "total_memory", "legendFormat": "Total Memory" }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_memory - free_memory", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    { "expr": "tps", "legendFormat": "TPS" }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tps", "legendFormat": "TPS" }
   ]
  },
  {
   "title": "MSPT ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "mspt", "legendFormat": "MSPT" }
   ]
  },
  {
   "title": "MSPT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mspt", "legendFormat": "mspt" }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "player_count", "legendFormat": "Players" }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "player_count" }
   ]
  },
  {
   "title": "Entity Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 35 },
   "targets": [
    { "expr": "entity_count_world", "legendFormat": "{{world}}" }
   ]
  },
  {
   "title": "Entity Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "entity_count" }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 42 },
   "targets": [
    { "expr": "loaded_chunks_world", "legendFormat": "{{world}}" }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "loaded_chunks" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "disk_space_world", "legendFormat": "{{world}}" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(disk_space_world)" }
   ]
  }
 ]
}